project:
  type: website
  output-dir: docs

website:
  title: "CoastWatch Primary Productivity Project"
  navbar:
    logo: images/NOAA_logo.png
    href: https://coastwatch.noaa.gov/cwn/index.html

format:
  html:
    theme: cosmo
    css: styles.css

